### ISSUE TITLE
splash damages are weird.

### ISSUE THREAD

**Issue by cfnnit** [Zabaniya001/att_fireballs#1]
https://youtu.be/RYF3bdOKUnI

test setup
`"fire wizard spells rage"				"max_rage=1000.0 max_damage_25%=1.0 max_damage_50%=1000.0 max_damage_75%=1000.0 max_damage_100%=1000.0"`

**Comment by tsuza** [comment]
Thank you for letting me know! Gonna fix it tomorrow.

**Comment by tsuza** [comment]
This took slightly more than I expected. I got busy so I put this aside. Fixed it in the latest commit. badd427e506a997600348bf9c14daf3c7c504c50
